name: Compile Stylus to CSS and Slim to HTML
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run stylus 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install stylus -g
    - run: stylus *.styl
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run slim
      run: |
       gem install slim
       slimrb *.slim --pretty > out.html
    - name: Commit changes
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Compile Stylus to CSS and Slim to HTML"
          git push
